// Generated by CoffeeScript 1.6.3
(function() {
  var allowCrossDomain, app, express, project, single;

  express = require('express');

  app = express();

  allowCrossDomain = function(req, res, next) {
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE');
    res.header('Access-Control-Allow-Headers', 'Content-Type, Authorization');
    if ('OPTIONS' === req.method) {
      return res.send(200);
    } else {
      return next();
    }
  };

  app.configure(function() {
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    return app.use(allowCrossDomain);
  });

  app.configure("development", function() {
    app.use(express.logger('dev'));
    return app.use(express.errorHandler({
      dumpExceptions: true,
      showStack: true
    }));
  });

  app.configure("production", function() {
    return app.use(express.errorHandler());
  });

  project = {
    projects: [
      {
        id: 1,
        name: 'project 1'
      }, {
        id: 2,
        name: 'project 2'
      }, {
        id: 3,
        name: 'project 3'
      }
    ]
  };

  single = {
    project: {
      id: 1,
      name: 'project 1'
    }
  };

  app.get('/projects', function(req, res) {
    return res.json(project);
  });

  app.get('/projects/:id', function(req, res) {
    return res.json(single);
  });

  app.listen(3000);

}).call(this);
